name: Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  ruminate:
  runs-on: ubuntu-22
  steps:
  - name: step_one
    run: |
      printenv
      /usr/bin/true
  - name: step_two:
    run: |
      echo "This is step 2"
      /usr/bin/false
  - name: step_three:
    run: |
      echo "There is no step 3"
  
